# Book settings
######################################################################################
# Book settings
title: "Climate Laboratory Book"
author: Brian Rose
email: paustin@eoas.ubc.ca
description: >- # this means to ignore newlines until "baseurl:"
  Climate Laboratory

execute:
  execute_notebooks: off
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - dollarmath
    - html_admonition
    - html_image
    
  
exclude_patterns: ["*ipynb"]

repository:
  url: https://github.com/phaustin/ClimateLaboratoryBook
  branch: jb
  path_to_book: content

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url: https://jupyterhub.eoas.ubc.ca

html:
  home_page_in_navbar: true
  baseurl: https://phaustin.github.io/ClimateLaboratoryBook
  
