# Book settings
######################################################################################
# Book settings
title: "ATSC 301"
author: Philip Austin
email: paustin@eoas.ubc.ca
description: >- # this means to ignore newlines until "baseurl:"
  Website for EOAS ATSC 301

execute:
  execute_notebooks: cache

exclude_patterns: ["*ipynb"]

repository:
  url: https://github.com/phaustin/a301_2020
  branch: master
  path_to_book: notebooks

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  jupyterhub_url: https://a301_hub.eoas.ubc.ca
  
html:
  home_page_in_navbar: true
  baseurl: https://a301_web.eoas.ubc.ca
